from django.urls import path

from apps.main.views import (  # Super Challenge views
    AllChallengesCalendarAPIView,
    AllSuperChallengesCalendarAPIView,
    Challenge30DaysPlusStreakDetailView,
    Challenge30DaysPlusStreakView,
    ChallengeAwardListView,
    ChallengeCalendarAPIView,
    ChallengeLeaderboardAPIView,
    ChallengeListAPIView,
    SuperChallengeAwardListView,
    SuperChallengeCalendarAPIView,
    SuperChallengeDetailAPIView,
    SuperChallengeListAPIView,
    UpdateUserChallengeStreaksAPIView,
    UserChallengeCompletionAPIView,
    UserChallengeCreateAPIView,
    UserChallengeDeleteAPIView,
    UserChallengeDetailAPIView,
    UserChallengeListAPIView,
    UserSuperChallengeDetailAPIView,
    UserSuperChallengeListAPIView,
)

app_name = "main"

urlpatterns = [
    # Challenge URLs
    path("challenges/", ChallengeListAPIView.as_view(), name="challenge-list"),
    # User Challenge URLs
    path(
        "user-challenges/",
        UserChallengeListAPIView.as_view(),
        name="user-challenge-list",
    ),
    path(
        "user-challenges/create/",
        UserChallengeCreateAPIView.as_view(),
        name="user-challenge-create",
    ),
    path(
        "user-challenges/<int:id>/",
        UserChallengeDetailAPIView.as_view(),
        name="user-challenge-detail",
    ),
    path(
        "user-challenges/<int:id>/delete/",
        UserChallengeDeleteAPIView.as_view(),
        name="user-challenge-delete",
    ),
    path(
        "challenges/<int:id>/complete/",
        UserChallengeCompletionAPIView.as_view(),
        name="challenge-complete",
    ),
    path(
        "user-challenges/<int:id>/calendar/",
        ChallengeCalendarAPIView.as_view(),
        name="user-challenge-calendar",
    ),
    path(
        "challenges/calendar/",
        AllChallengesCalendarAPIView.as_view(),
        name="all-challenges-calendar",
    ),
    path(
        "challenges/<int:id>/leaderboard/",
        ChallengeLeaderboardAPIView.as_view(),
        name="challenge-leaderboard",
    ),
    path(
        "challenges/30-days-plus-streaks/",
        Challenge30DaysPlusStreakView.as_view(),
        name="challenge-30-days-plus-streaks",
    ),
    path(
        "challenges/<int:id>/30-days-plus-streaks/",
        Challenge30DaysPlusStreakDetailView.as_view(),
        name="challenge-30-days-plus-streaks-detail",
    ),
    path(
        "challenges/awards/",
        ChallengeAwardListView.as_view(),
        name="challenge-awards",
    ),
    path(
        "admin/update-streaks/",
        UpdateUserChallengeStreaksAPIView.as_view(),
        name="update-user-challenge-streaks",
    ),
    # Super Challenge URLs
    path(
        "super-challenges/",
        SuperChallengeListAPIView.as_view(),
        name="super-challenge-list",
    ),
    path(
        "super-challenges/<int:id>/",
        SuperChallengeDetailAPIView.as_view(),
        name="super-challenge-detail",
    ),
    path(
        "user-super-challenges/",
        UserSuperChallengeListAPIView.as_view(),
        name="user-super-challenge-list",
    ),
    path(
        "user-super-challenges/<int:id>/",
        UserSuperChallengeDetailAPIView.as_view(),
        name="user-super-challenge-detail",
    ),
    path(
        "user-super-challenges/<int:id>/calendar/",
        SuperChallengeCalendarAPIView.as_view(),
        name="user-super-challenge-calendar",
    ),
    path(
        "super-challenges/calendar/",
        AllSuperChallengesCalendarAPIView.as_view(),
        name="all-super-challenges-calendar",
    ),
    path(
        "super-challenges/awards/",
        SuperChallengeAwardListView.as_view(),
        name="super-challenge-awards",
    ),
]
