# Generated by Django 5.1.6 on 2025-03-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_is_onboarding_finished"),
    ]

    operations = [
        migrations.AddField(
            model_name="timezone",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="timezone",
            name="name_ru",
            field=models.CharField(max_length=100, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="timezone",
            name="name_uz",
            field=models.CharField(max_length=100, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="timezone",
            name="name_uz_cy",
            field=models.CharField(max_length=100, null=True, verbose_name="Name"),
        ),
    ]
