# Generated by Django 5.1.6 on 2025-03-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_telegram_id_alter_user_telegram_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("uz", "Uzbek"),
                    ("ru", "Russian"),
                    ("uz-cy", "Uzbek Cyrillic"),
                ],
                default="uz",
                max_length=100,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Telegram ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Telegram Username"
            ),
        ),
    ]
