# Generated by Django 5.1.6 on 2025-03-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_first_name_alter_user_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_telegram_channel_member",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether the user is a member of the Telegram channel. Defaults to True and is set to False when confirmed not a member.",
                verbose_name="Is Telegram Channel Member",
            ),
        ),
    ]
