# Generated by Django 5.1.6 on 2025-02-28 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0002_faq"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "ordering": ["order"],
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["order"],
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.AlterModelOptions(
            name="useranswer",
            options={
                "verbose_name": "User Answer",
                "verbose_name_plural": "User Answers",
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="text_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Text"),
        ),
        migrations.AddField(
            model_name="answer",
            name="text_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Text"),
        ),
        migrations.AddField(
            model_name="answer",
            name="text_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Text"),
        ),
        migrations.AddField(
            model_name="answer",
            name="text_uz_cy",
            field=models.CharField(max_length=255, null=True, verbose_name="Text"),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_en",
            field=models.TextField(null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_ru",
            field=models.TextField(null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_uz",
            field=models.TextField(null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_uz_cy",
            field=models.TextField(null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Question"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Question"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Question"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_uz_cy",
            field=models.CharField(max_length=255, null=True, verbose_name="Question"),
        ),
        migrations.AddField(
            model_name="question",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="question",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="question",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="question",
            name="title_uz_cy",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="onboarding.question",
                verbose_name="Question",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.CharField(max_length=255, verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(verbose_name="Answer"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(max_length=255, verbose_name="Question"),
        ),
        migrations.AlterField(
            model_name="question",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_selections",
                to="onboarding.answer",
                verbose_name="Answer",
            ),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to="onboarding.question",
                verbose_name="Question",
            ),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboarding_answers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
