# Generated by Django 5.1.6 on 2025-03-11 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0022_superchallenge_superchallengeaward_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeNotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Notification message to be sent to users at challenge start time",
                        verbose_name="Message",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "challenge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_template",
                        to="main.challenge",
                        verbose_name="Challenge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Challenge Notification Template",
                "verbose_name_plural": "Challenge Notification Templates",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("challenge", "Challenge"),
                            ("super_challenge_general", "Super Challenge General"),
                            ("super_challenge_warning", "Super Challenge Warning"),
                            ("super_challenge_failure", "Super Challenge Failure"),
                        ],
                        max_length=50,
                        verbose_name="Notification Type",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Sent at"),
                ),
                ("is_sent", models.BooleanField(default=False, verbose_name="Is sent")),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to="main.challenge",
                        verbose_name="Challenge",
                    ),
                ),
                (
                    "super_challenge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to="main.superchallenge",
                        verbose_name="Super Challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="SuperChallengeNotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "general_message",
                    models.TextField(
                        help_text="General notification message sent to active users",
                        verbose_name="General Message",
                    ),
                ),
                (
                    "progress_warning_message",
                    models.TextField(
                        help_text="Warning message sent when user hasn't completed all challenges",
                        verbose_name="Progress Warning Message",
                    ),
                ),
                (
                    "failure_message",
                    models.TextField(
                        help_text="Message sent when user has failed the super challenge",
                        verbose_name="Failure Message",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "super_challenge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_template",
                        to="main.superchallenge",
                        verbose_name="Super Challenge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Super Challenge Notification Template",
                "verbose_name_plural": "Super Challenge Notification Templates",
            },
        ),
    ]
