# Generated by Django 5.1.6 on 2025-02-28 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="challenge",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Challenge",
                "verbose_name_plural": "Challenges",
            },
        ),
        migrations.AlterModelOptions(
            name="challengeaward",
            options={
                "ordering": ["-awarded_at"],
                "verbose_name": "Challenge Award",
                "verbose_name_plural": "Challenge Awards",
            },
        ),
        migrations.AlterModelOptions(
            name="challengecompletion",
            options={
                "ordering": ["-completed_at"],
                "verbose_name": "Challenge Completion",
                "verbose_name_plural": "Challenge Completions",
            },
        ),
        migrations.AlterModelOptions(
            name="userchallenge",
            options={
                "ordering": ["-current_streak", "-highest_streak"],
                "verbose_name": "User Challenge",
                "verbose_name_plural": "User Challenges",
            },
        ),
        migrations.AddField(
            model_name="challenge",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="challenge",
            name="title_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="challenge",
            name="title_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="challenge",
            name="title_uz_cy",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="end_time",
            field=models.TimeField(verbose_name="End time"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="icon",
            field=models.ImageField(upload_to="challenge_icons/", verbose_name="Icon"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="start_time",
            field=models.TimeField(verbose_name="Start time"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="video_instruction_url",
            field=models.URLField(verbose_name="Video instruction URL"),
        ),
        migrations.AlterField(
            model_name="challengeaward",
            name="awarded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Awarded at"),
        ),
        migrations.AlterField(
            model_name="challengeaward",
            name="user_challenge",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="award",
                to="main.userchallenge",
                verbose_name="User challenge",
            ),
        ),
        migrations.AlterField(
            model_name="challengecompletion",
            name="completed_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Completed at"),
        ),
        migrations.AlterField(
            model_name="challengecompletion",
            name="user_challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completions",
                to="main.userchallenge",
                verbose_name="User challenge",
            ),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_challenges",
                to="main.challenge",
                verbose_name="Challenge",
            ),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="current_streak",
            field=models.PositiveIntegerField(default=0, verbose_name="Current streak"),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="highest_streak",
            field=models.PositiveIntegerField(default=0, verbose_name="Highest streak"),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="last_completion_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Last completion date"
            ),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Started at"),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="total_completions",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total completions"
            ),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_challenges",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
