# Generated by Django 5.1.6 on 2025-02-28 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_challenge_options_alter_challengeaward_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChallengeCompletion",
            new_name="UserChallengeCompletion",
        ),
        migrations.AlterModelOptions(
            name="userchallengecompletion",
            options={
                "ordering": ["-completed_at"],
                "verbose_name": "User Challenge Completion",
                "verbose_name_plural": "User Challenge Completions",
            },
        ),
    ]
