# Generated by Django 5.1.6 on 2025-02-28 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_rename_challengecompletion_userchallengecompletion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="challengeaward",
            options={},
        ),
        migrations.RemoveField(
            model_name="challengeaward",
            name="awarded_at",
        ),
        migrations.RemoveField(
            model_name="challengeaward",
            name="user_challenge",
        ),
        migrations.AddField(
            model_name="challenge",
            name="award_icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="award_icons/",
                verbose_name="Award Icon",
            ),
        ),
        migrations.AddField(
            model_name="challengeaward",
            name="challenge",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="award",
                to="main.challenge",
            ),
        ),
        migrations.CreateModel(
            name="UserAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_awards",
                        to="main.challengeaward",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "award")},
            },
        ),
    ]
