# Generated by Django 5.1.6 on 2025-02-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_challengeaward_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="video_instruction_title",
            field=models.CharField(
                blank=True,
                help_text="Title for the instruction video",
                max_length=255,
                null=True,
                verbose_name="Video instruction title",
            ),
        ),
    ]
