# Generated by Django 5.1.6 on 2025-02-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_challenge_video_instruction_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="calendar_icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="challenge_calendar_icons/",
                verbose_name="Calendar Icon",
            ),
        ),
    ]
