# Generated by Django 5.1.6 on 2025-03-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_challenge_calendar_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "title_en",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "title_uz",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "title_uz_cy",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "icon",
                    models.ImageField(
                        upload_to="tournament_icons/", verbose_name="Icon"
                    ),
                ),
                ("finish_date", models.DateTimeField(verbose_name="Finish Date")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "challenges",
                    models.ManyToManyField(
                        related_name="tournaments",
                        to="main.challenge",
                        verbose_name="Challenges",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament",
                "verbose_name_plural": "Tournaments",
                "ordering": ["-created_at"],
            },
        ),
    ]
