# Generated by Django 5.1.6 on 2025-03-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_tournament"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="rules",
            field=models.TextField(blank=True, null=True, verbose_name="Rules"),
        ),
    ]
