# Generated by Django 5.1.6 on 2025-03-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_challenge_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userchallengecompletion",
            name="completed_at",
            field=models.DateTimeField(verbose_name="Completed at"),
        ),
    ]
