# Generated by Django 5.1.6 on 2025-03-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_userchallengecompletion_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="rules_en",
            field=models.TextField(blank=True, null=True, verbose_name="Rules"),
        ),
        migrations.AddField(
            model_name="challenge",
            name="rules_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Rules"),
        ),
        migrations.AddField(
            model_name="challenge",
            name="rules_uz",
            field=models.TextField(blank=True, null=True, verbose_name="Rules"),
        ),
        migrations.AddField(
            model_name="challenge",
            name="rules_uz_cy",
            field=models.TextField(blank=True, null=True, verbose_name="Rules"),
        ),
    ]
