# Generated by Django 5.1.6 on 2025-03-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_challenge_rules_en_challenge_rules_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchallenge",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
    ]
