# Generated by Django 5.1.6 on 2025-03-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_tournament_award_icon_tournament_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchallengecompletion",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
    ]
