# Generated by Django 5.1.6 on 2025-03-06 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_userchallengecompletion_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userchallenge",
            name="is_active",
        ),
    ]
