# Generated by Django 5.1.6 on 2025-03-07 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_remove_userchallenge_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertournament",
            name="user_challenge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_tournaments",
                to="main.userchallenge",
                verbose_name="User challenge",
            ),
        ),
    ]
