# Generated by Django 5.1.6 on 2025-03-07 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_usertournament_user_challenge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertournament",
            name="user_challenge",
        ),
    ]
