# Generated by Django 5.1.6 on 2025-03-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_remove_usertournament_user_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="calendar_icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tournament_calendar_icons/",
                verbose_name="Calendar Icon",
            ),
        ),
    ]
