# Generated by Django 5.1.6 on 2025-03-10 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_tournament_calendar_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, remove all unique constraints
        migrations.AlterUniqueTogether(
            name="usertournament",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="usertournamentday",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="useraward",
            unique_together={("user", "challenge_award")},
        ),
        
        # Then remove all foreign key fields
        migrations.RemoveField(
            model_name="usertournamentday",
            name="completed_challenges",
        ),
        migrations.RemoveField(
            model_name="usertournamentday",
            name="user_tournament",
        ),
        migrations.RemoveField(
            model_name="usertournament",
            name="tournament",
        ),
        migrations.RemoveField(
            model_name="usertournament",
            name="user",
        ),
        migrations.RemoveField(
            model_name="tournamentaward",
            name="tournament",
        ),
        migrations.RemoveField(
            model_name="useraward",
            name="tournament_award",
        ),
        
        # Finally delete the models
        migrations.DeleteModel(
            name="UserTournamentDay",
        ),
        migrations.DeleteModel(
            name="UserTournament",
        ),
        migrations.DeleteModel(
            name="Tournament",
        ),
        migrations.DeleteModel(
            name="TournamentAward",
        ),
    ]
