# Generated by Django 5.1.6 on 2025-03-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_remove_tournamentaward_tournament_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchallenge",
            name="has_award",
            field=models.BooleanField(default=False, verbose_name="Has award"),
        ),
        migrations.AddField(
            model_name="userchallenge",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
    ]
