# Generated by Django 5.1.6 on 2025-03-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="custommessage",
            name="is_attach_link",
            field=models.BooleanField(default=False, verbose_name="Is attach link"),
        ),
    ]
