# Generated by Django 5.1.6 on 2025-03-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_bot", "0002_custommessage_is_attach_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custommessage",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
    ]
