# Generated by Django 5.1.6 on 2025-03-09 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_tournament_calendar_icon"),
        ("telegram_bot", "0003_alter_custommessage_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="custommessage",
            name="challenge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_messages",
                to="main.challenge",
                verbose_name="Challenge",
            ),
        ),
    ]
